# Generated by Django 5.2.4 on 2025-07-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view data'), ('can_create', 'Can create data'), ('can_edit', 'Can edit data'), ('can_delete', 'Can delete data')]},
        ),
    ]
