# Generated by Django 5.2.4 on 2025-07-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view custom user'), ('can_create', 'Can create custom user'), ('can_edit', 'Can edit custom user'), ('can_delete', 'Can delete custom user')]},
        ),
    ]
