# Generated by Django 5.2.4 on 2025-08-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ser',
            new_name='user',
        ),
    ]
